@startuml


class Persona{
--
- nombre:  String
- apellido:  String
- domicilio: String
--

+Persona()
+Persona(String,String,String)

+setNombre(String):void
+setApellido(String):void
+setDocimicilio(String):void

+getNombre():String
+getApellido():String
+getDocimicilio():String

+toString():String
+mostrarNombreApellido():void
}
@enduml